name: vrcx-0-bin

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: vrcx-0
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    container: archlinux/archlinux:latest
    steps:
      - name: Setup
        run: |
          pacman -Syu --noconfirm git devtools curl jq openssh
          sudo useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers

      - uses: actions/checkout@v7

      - name: Get latest release
        id: latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: Map1en
          repo: VRCX-0
          excludes: prerelease, draft

      - name: Check if out of date
        id: check
        run: |
          ver="${{ steps.latest.outputs.release }}"
          ver="${ver#v}"
          cur="$(sed -n "s/^pkgver='//p" "${{ github.workflow }}/PKGBUILD" | sed "s/'\$//")"
          echo "version=${ver}" >> "$GITHUB_OUTPUT"
          [ "$ver" != "$cur" ] && echo "out_of_date=true" >> "$GITHUB_OUTPUT" || echo "out_of_date=false" >> "$GITHUB_OUTPUT"

      - name: Bump & commit
        if: steps.check.outputs.out_of_date == 'true'
        uses: ./.github/actions/bump-aur
        with:
          version: ${{ steps.check.outputs.version }}
          url: "https://github.com/Map1en/VRCX-0/releases/download/${{ steps.latest.outputs.release }}/VRCX-0_${{ steps.check.outputs.version }}_linux_x86_64.deb"
          dir: "${{ github.workflow }}/"
      - name: Commit & push
        if: steps.check.outputs.out_of_date == 'true'
        working-directory: ${{ github.workspace }}
        run: |
          pwd
          ls -lna
          ls -lna ..
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "${{ github.workflow }}/PKGBUILD" "${{ github.workflow }}/.SRCINFO"
          git commit -m "Update to ${{ steps.check.outputs.version }}"
          git push origin HEAD

  aur_push:
    needs: update
    if: needs.update.outputs.out_of_date == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v4.2.0
        with:
          pkgname: ${{ github.workflow }}
          pkgbuild: "./${{ github.workflow }}/PKGBUILD"
          commit_username: github-actions[bot]
          commit_email: 41898282+github-actions[bot]@users.noreply.github.com
          ssh_private_key: ${{ secrets.AUR_SSH_KEY }}
          commit_message: Update
          ssh_keyscan_types: rsa,ecdsa,ed25519
